# MLOPS cicd pipeline.

name: Iris MLOps CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train-register-model:
    name: train-and-register-model
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create Data Directory
      run: mkdir -p data model

    - name: Run Data Ingestion
      run: python src/ingest_data.py

    - name: Train and Tune Model
      run: python src/train_model.py

    - name: Register Model
      run: python src/register_model.py
  
  Build-and-Push-Model:
    name: Build and Push Docker Image
    needs: train-register-model
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/iris-ml-api:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/iris-ml-api:latest

  deploy:
    name: Deploy to Kubernetes
    needs: Build-and-Push-Model
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
          aws-region: ap-south-1

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: latest

    - name: Update kubeconfig for EKS
      run: aws eks update-kubeconfig --region ap-south-1 --name MLOPs-cluster

    - name: Configure kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG_DATA }}" > $HOME/.kube/config

    - name: Run K8s command to deploy
      run: |
        kubectl apply -f ./k8s/ds.yml --validate=false